# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shiva/core/communication_objects/env_specs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shiva/core/communication_objects/env_specs.proto',
  package='communication_objects',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n0shiva/core/communication_objects/env_specs.proto\x12\x15\x63ommunication_objects\"{\n\x10\x45nvironmentSpecs\x12\x19\n\x11observation_space\x18\x01 \x01(\x05\x12\x14\n\x0c\x61\x63tion_space\x18\x02 \x01(\x05\x12\x15\n\rnum_instances\x18\x03 \x01(\x05\x12\x1f\n\x17num_agents_per_instance\x18\x04 \x01(\x05\x62\x06proto3')
)




_ENVIRONMENTSPECS = _descriptor.Descriptor(
  name='EnvironmentSpecs',
  full_name='communication_objects.EnvironmentSpecs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='observation_space', full_name='communication_objects.EnvironmentSpecs.observation_space', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_space', full_name='communication_objects.EnvironmentSpecs.action_space', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_instances', full_name='communication_objects.EnvironmentSpecs.num_instances', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_agents_per_instance', full_name='communication_objects.EnvironmentSpecs.num_agents_per_instance', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=75,
  serialized_end=198,
)

DESCRIPTOR.message_types_by_name['EnvironmentSpecs'] = _ENVIRONMENTSPECS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnvironmentSpecs = _reflection.GeneratedProtocolMessageType('EnvironmentSpecs', (_message.Message,), {
  'DESCRIPTOR' : _ENVIRONMENTSPECS,
  '__module__' : 'shiva.core.communication_objects.env_specs_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.EnvironmentSpecs)
  })
_sym_db.RegisterMessage(EnvironmentSpecs)


# @@protoc_insertion_point(module_scope)
