# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shiva/core/communication_objects/env_step_output.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shiva.core.communication_objects import agent_state_pb2 as shiva_dot_core_dot_communication__objects_dot_agent__state__pb2
from shiva.core.communication_objects import env_metrics_pb2 as shiva_dot_core_dot_communication__objects_dot_env__metrics__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='shiva/core/communication_objects/env_step_output.proto',
  package='communication_objects',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n6shiva/core/communication_objects/env_step_output.proto\x12\x15\x63ommunication_objects\x1a\x32shiva/core/communication_objects/agent_state.proto\x1a\x32shiva/core/communication_objects/env_metrics.proto\"\x90\x04\n\rEnvStepOutput\x12K\n\x0c\x61gent_states\x18\x01 \x03(\x0b\x32\x35.communication_objects.EnvStepOutput.AgentStatesEntry\x12M\n\ragent_metrics\x18\x02 \x03(\x0b\x32\x36.communication_objects.EnvStepOutput.AgentMetricsEntry\x1a\x43\n\x10ListAgentsStates\x12/\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32!.communication_objects.AgentState\x1a\x46\n\x11ListAgentsMetrics\x12\x31\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32#.communication_objects.AgentMetrics\x1ai\n\x10\x41gentStatesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x44\n\x05value\x18\x02 \x01(\x0b\x32\x35.communication_objects.EnvStepOutput.ListAgentsStates:\x02\x38\x01\x1ak\n\x11\x41gentMetricsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x45\n\x05value\x18\x02 \x01(\x0b\x32\x36.communication_objects.EnvStepOutput.ListAgentsMetrics:\x02\x38\x01\x62\x06proto3')
  ,
  dependencies=[shiva_dot_core_dot_communication__objects_dot_agent__state__pb2.DESCRIPTOR,shiva_dot_core_dot_communication__objects_dot_env__metrics__pb2.DESCRIPTOR,])




_ENVSTEPOUTPUT_LISTAGENTSSTATES = _descriptor.Descriptor(
  name='ListAgentsStates',
  full_name='communication_objects.EnvStepOutput.ListAgentsStates',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='communication_objects.EnvStepOutput.ListAgentsStates.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=359,
  serialized_end=426,
)

_ENVSTEPOUTPUT_LISTAGENTSMETRICS = _descriptor.Descriptor(
  name='ListAgentsMetrics',
  full_name='communication_objects.EnvStepOutput.ListAgentsMetrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='communication_objects.EnvStepOutput.ListAgentsMetrics.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=428,
  serialized_end=498,
)

_ENVSTEPOUTPUT_AGENTSTATESENTRY = _descriptor.Descriptor(
  name='AgentStatesEntry',
  full_name='communication_objects.EnvStepOutput.AgentStatesEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='communication_objects.EnvStepOutput.AgentStatesEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='communication_objects.EnvStepOutput.AgentStatesEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=500,
  serialized_end=605,
)

_ENVSTEPOUTPUT_AGENTMETRICSENTRY = _descriptor.Descriptor(
  name='AgentMetricsEntry',
  full_name='communication_objects.EnvStepOutput.AgentMetricsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='communication_objects.EnvStepOutput.AgentMetricsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='communication_objects.EnvStepOutput.AgentMetricsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=607,
  serialized_end=714,
)

_ENVSTEPOUTPUT = _descriptor.Descriptor(
  name='EnvStepOutput',
  full_name='communication_objects.EnvStepOutput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_states', full_name='communication_objects.EnvStepOutput.agent_states', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='agent_metrics', full_name='communication_objects.EnvStepOutput.agent_metrics', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ENVSTEPOUTPUT_LISTAGENTSSTATES, _ENVSTEPOUTPUT_LISTAGENTSMETRICS, _ENVSTEPOUTPUT_AGENTSTATESENTRY, _ENVSTEPOUTPUT_AGENTMETRICSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=714,
)

_ENVSTEPOUTPUT_LISTAGENTSSTATES.fields_by_name['data'].message_type = shiva_dot_core_dot_communication__objects_dot_agent__state__pb2._AGENTSTATE
_ENVSTEPOUTPUT_LISTAGENTSSTATES.containing_type = _ENVSTEPOUTPUT
_ENVSTEPOUTPUT_LISTAGENTSMETRICS.fields_by_name['data'].message_type = shiva_dot_core_dot_communication__objects_dot_env__metrics__pb2._AGENTMETRICS
_ENVSTEPOUTPUT_LISTAGENTSMETRICS.containing_type = _ENVSTEPOUTPUT
_ENVSTEPOUTPUT_AGENTSTATESENTRY.fields_by_name['value'].message_type = _ENVSTEPOUTPUT_LISTAGENTSSTATES
_ENVSTEPOUTPUT_AGENTSTATESENTRY.containing_type = _ENVSTEPOUTPUT
_ENVSTEPOUTPUT_AGENTMETRICSENTRY.fields_by_name['value'].message_type = _ENVSTEPOUTPUT_LISTAGENTSMETRICS
_ENVSTEPOUTPUT_AGENTMETRICSENTRY.containing_type = _ENVSTEPOUTPUT
_ENVSTEPOUTPUT.fields_by_name['agent_states'].message_type = _ENVSTEPOUTPUT_AGENTSTATESENTRY
_ENVSTEPOUTPUT.fields_by_name['agent_metrics'].message_type = _ENVSTEPOUTPUT_AGENTMETRICSENTRY
DESCRIPTOR.message_types_by_name['EnvStepOutput'] = _ENVSTEPOUTPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnvStepOutput = _reflection.GeneratedProtocolMessageType('EnvStepOutput', (_message.Message,), {

  'ListAgentsStates' : _reflection.GeneratedProtocolMessageType('ListAgentsStates', (_message.Message,), {
    'DESCRIPTOR' : _ENVSTEPOUTPUT_LISTAGENTSSTATES,
    '__module__' : 'shiva.core.communication_objects.env_step_output_pb2'
    # @@protoc_insertion_point(class_scope:communication_objects.EnvStepOutput.ListAgentsStates)
    })
  ,

  'ListAgentsMetrics' : _reflection.GeneratedProtocolMessageType('ListAgentsMetrics', (_message.Message,), {
    'DESCRIPTOR' : _ENVSTEPOUTPUT_LISTAGENTSMETRICS,
    '__module__' : 'shiva.core.communication_objects.env_step_output_pb2'
    # @@protoc_insertion_point(class_scope:communication_objects.EnvStepOutput.ListAgentsMetrics)
    })
  ,

  'AgentStatesEntry' : _reflection.GeneratedProtocolMessageType('AgentStatesEntry', (_message.Message,), {
    'DESCRIPTOR' : _ENVSTEPOUTPUT_AGENTSTATESENTRY,
    '__module__' : 'shiva.core.communication_objects.env_step_output_pb2'
    # @@protoc_insertion_point(class_scope:communication_objects.EnvStepOutput.AgentStatesEntry)
    })
  ,

  'AgentMetricsEntry' : _reflection.GeneratedProtocolMessageType('AgentMetricsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ENVSTEPOUTPUT_AGENTMETRICSENTRY,
    '__module__' : 'shiva.core.communication_objects.env_step_output_pb2'
    # @@protoc_insertion_point(class_scope:communication_objects.EnvStepOutput.AgentMetricsEntry)
    })
  ,
  'DESCRIPTOR' : _ENVSTEPOUTPUT,
  '__module__' : 'shiva.core.communication_objects.env_step_output_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.EnvStepOutput)
  })
_sym_db.RegisterMessage(EnvStepOutput)
_sym_db.RegisterMessage(EnvStepOutput.ListAgentsStates)
_sym_db.RegisterMessage(EnvStepOutput.ListAgentsMetrics)
_sym_db.RegisterMessage(EnvStepOutput.AgentStatesEntry)
_sym_db.RegisterMessage(EnvStepOutput.AgentMetricsEntry)


_ENVSTEPOUTPUT_AGENTSTATESENTRY._options = None
_ENVSTEPOUTPUT_AGENTMETRICSENTRY._options = None
# @@protoc_insertion_point(module_scope)
