# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shiva/core/communication_objects/env_step_input.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shiva.core.communication_objects import helpers_pb2 as shiva_dot_core_dot_communication__objects_dot_helpers__pb2
from shiva.core.communication_objects import env_command_pb2 as shiva_dot_core_dot_communication__objects_dot_env__command__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='shiva/core/communication_objects/env_step_input.proto',
  package='communication_objects',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n5shiva/core/communication_objects/env_step_input.proto\x12\x15\x63ommunication_objects\x1a.shiva/core/communication_objects/helpers.proto\x1a\x32shiva/core/communication_objects/env_command.proto\"\xf9\x03\n\x0c\x45nvStepInput\x12L\n\ragent_actions\x18\x01 \x03(\x0b\x32\x35.communication_objects.EnvStepInput.AgentActionsEntry\x12:\n\x07\x63ommand\x18\x02 \x01(\x0e\x32).communication_objects.EnvironmentCommand\x1a\xf2\x01\n\x11ListAgentsActions\x12N\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32@.communication_objects.EnvStepInput.ListAgentsActions.SingleData\x1a\x8c\x01\n\nSingleData\x12\x38\n\x0bvalues_ints\x18\x01 \x01(\x0b\x32!.communication_objects.ListOfIntsH\x00\x12<\n\rvalues_floats\x18\x02 \x01(\x0b\x32#.communication_objects.ListOfFloatsH\x00\x42\x06\n\x04\x64\x61ta\x1aj\n\x11\x41gentActionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x44\n\x05value\x18\x02 \x01(\x0b\x32\x35.communication_objects.EnvStepInput.ListAgentsActions:\x02\x38\x01\x62\x06proto3')
  ,
  dependencies=[shiva_dot_core_dot_communication__objects_dot_helpers__pb2.DESCRIPTOR,shiva_dot_core_dot_communication__objects_dot_env__command__pb2.DESCRIPTOR,])




_ENVSTEPINPUT_LISTAGENTSACTIONS_SINGLEDATA = _descriptor.Descriptor(
  name='SingleData',
  full_name='communication_objects.EnvStepInput.ListAgentsActions.SingleData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='values_ints', full_name='communication_objects.EnvStepInput.ListAgentsActions.SingleData.values_ints', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values_floats', full_name='communication_objects.EnvStepInput.ListAgentsActions.SingleData.values_floats', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='data', full_name='communication_objects.EnvStepInput.ListAgentsActions.SingleData.data',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=438,
  serialized_end=578,
)

_ENVSTEPINPUT_LISTAGENTSACTIONS = _descriptor.Descriptor(
  name='ListAgentsActions',
  full_name='communication_objects.EnvStepInput.ListAgentsActions',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='communication_objects.EnvStepInput.ListAgentsActions.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ENVSTEPINPUT_LISTAGENTSACTIONS_SINGLEDATA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=336,
  serialized_end=578,
)

_ENVSTEPINPUT_AGENTACTIONSENTRY = _descriptor.Descriptor(
  name='AgentActionsEntry',
  full_name='communication_objects.EnvStepInput.AgentActionsEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='communication_objects.EnvStepInput.AgentActionsEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='communication_objects.EnvStepInput.AgentActionsEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=580,
  serialized_end=686,
)

_ENVSTEPINPUT = _descriptor.Descriptor(
  name='EnvStepInput',
  full_name='communication_objects.EnvStepInput',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='agent_actions', full_name='communication_objects.EnvStepInput.agent_actions', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='command', full_name='communication_objects.EnvStepInput.command', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ENVSTEPINPUT_LISTAGENTSACTIONS, _ENVSTEPINPUT_AGENTACTIONSENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=181,
  serialized_end=686,
)

_ENVSTEPINPUT_LISTAGENTSACTIONS_SINGLEDATA.fields_by_name['values_ints'].message_type = shiva_dot_core_dot_communication__objects_dot_helpers__pb2._LISTOFINTS
_ENVSTEPINPUT_LISTAGENTSACTIONS_SINGLEDATA.fields_by_name['values_floats'].message_type = shiva_dot_core_dot_communication__objects_dot_helpers__pb2._LISTOFFLOATS
_ENVSTEPINPUT_LISTAGENTSACTIONS_SINGLEDATA.containing_type = _ENVSTEPINPUT_LISTAGENTSACTIONS
_ENVSTEPINPUT_LISTAGENTSACTIONS_SINGLEDATA.oneofs_by_name['data'].fields.append(
  _ENVSTEPINPUT_LISTAGENTSACTIONS_SINGLEDATA.fields_by_name['values_ints'])
_ENVSTEPINPUT_LISTAGENTSACTIONS_SINGLEDATA.fields_by_name['values_ints'].containing_oneof = _ENVSTEPINPUT_LISTAGENTSACTIONS_SINGLEDATA.oneofs_by_name['data']
_ENVSTEPINPUT_LISTAGENTSACTIONS_SINGLEDATA.oneofs_by_name['data'].fields.append(
  _ENVSTEPINPUT_LISTAGENTSACTIONS_SINGLEDATA.fields_by_name['values_floats'])
_ENVSTEPINPUT_LISTAGENTSACTIONS_SINGLEDATA.fields_by_name['values_floats'].containing_oneof = _ENVSTEPINPUT_LISTAGENTSACTIONS_SINGLEDATA.oneofs_by_name['data']
_ENVSTEPINPUT_LISTAGENTSACTIONS.fields_by_name['data'].message_type = _ENVSTEPINPUT_LISTAGENTSACTIONS_SINGLEDATA
_ENVSTEPINPUT_LISTAGENTSACTIONS.containing_type = _ENVSTEPINPUT
_ENVSTEPINPUT_AGENTACTIONSENTRY.fields_by_name['value'].message_type = _ENVSTEPINPUT_LISTAGENTSACTIONS
_ENVSTEPINPUT_AGENTACTIONSENTRY.containing_type = _ENVSTEPINPUT
_ENVSTEPINPUT.fields_by_name['agent_actions'].message_type = _ENVSTEPINPUT_AGENTACTIONSENTRY
_ENVSTEPINPUT.fields_by_name['command'].enum_type = shiva_dot_core_dot_communication__objects_dot_env__command__pb2._ENVIRONMENTCOMMAND
DESCRIPTOR.message_types_by_name['EnvStepInput'] = _ENVSTEPINPUT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

EnvStepInput = _reflection.GeneratedProtocolMessageType('EnvStepInput', (_message.Message,), {

  'ListAgentsActions' : _reflection.GeneratedProtocolMessageType('ListAgentsActions', (_message.Message,), {

    'SingleData' : _reflection.GeneratedProtocolMessageType('SingleData', (_message.Message,), {
      'DESCRIPTOR' : _ENVSTEPINPUT_LISTAGENTSACTIONS_SINGLEDATA,
      '__module__' : 'shiva.core.communication_objects.env_step_input_pb2'
      # @@protoc_insertion_point(class_scope:communication_objects.EnvStepInput.ListAgentsActions.SingleData)
      })
    ,
    'DESCRIPTOR' : _ENVSTEPINPUT_LISTAGENTSACTIONS,
    '__module__' : 'shiva.core.communication_objects.env_step_input_pb2'
    # @@protoc_insertion_point(class_scope:communication_objects.EnvStepInput.ListAgentsActions)
    })
  ,

  'AgentActionsEntry' : _reflection.GeneratedProtocolMessageType('AgentActionsEntry', (_message.Message,), {
    'DESCRIPTOR' : _ENVSTEPINPUT_AGENTACTIONSENTRY,
    '__module__' : 'shiva.core.communication_objects.env_step_input_pb2'
    # @@protoc_insertion_point(class_scope:communication_objects.EnvStepInput.AgentActionsEntry)
    })
  ,
  'DESCRIPTOR' : _ENVSTEPINPUT,
  '__module__' : 'shiva.core.communication_objects.env_step_input_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.EnvStepInput)
  })
_sym_db.RegisterMessage(EnvStepInput)
_sym_db.RegisterMessage(EnvStepInput.ListAgentsActions)
_sym_db.RegisterMessage(EnvStepInput.ListAgentsActions.SingleData)
_sym_db.RegisterMessage(EnvStepInput.AgentActionsEntry)


_ENVSTEPINPUT_AGENTACTIONSENTRY._options = None
# @@protoc_insertion_point(module_scope)
