# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shiva/core/communication_objects/configs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shiva.core.communication_objects import enums_pb2 as shiva_dot_core_dot_communication__objects_dot_enums__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='shiva/core/communication_objects/configs.proto',
  package='communication_objects',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n.shiva/core/communication_objects/configs.proto\x12\x15\x63ommunication_objects\x1a,shiva/core/communication_objects/enums.proto\"\x96\x01\n\x0b\x43onfigProto\x12\x32\n\x04type\x18\x01 \x01(\x0e\x32$.communication_objects.ComponentType\x12\x32\n\tload_type\x18\x02 \x01(\x0e\x32\x1f.communication_objects.LoadType\x12\x11\n\tload_path\x18\x03 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x04 \x01(\tb\x06proto3')
  ,
  dependencies=[shiva_dot_core_dot_communication__objects_dot_enums__pb2.DESCRIPTOR,])




_CONFIGPROTO = _descriptor.Descriptor(
  name='ConfigProto',
  full_name='communication_objects.ConfigProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='communication_objects.ConfigProto.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='load_type', full_name='communication_objects.ConfigProto.load_type', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='load_path', full_name='communication_objects.ConfigProto.load_path', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='communication_objects.ConfigProto.data', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=270,
)

_CONFIGPROTO.fields_by_name['type'].enum_type = shiva_dot_core_dot_communication__objects_dot_enums__pb2._COMPONENTTYPE
_CONFIGPROTO.fields_by_name['load_type'].enum_type = shiva_dot_core_dot_communication__objects_dot_enums__pb2._LOADTYPE
DESCRIPTOR.message_types_by_name['ConfigProto'] = _CONFIGPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConfigProto = _reflection.GeneratedProtocolMessageType('ConfigProto', (_message.Message,), {
  'DESCRIPTOR' : _CONFIGPROTO,
  '__module__' : 'shiva.core.communication_objects.configs_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.ConfigProto)
  })
_sym_db.RegisterMessage(ConfigProto)


# @@protoc_insertion_point(module_scope)
