# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from shiva.core.communication_objects import helpers_pb2 as shiva_dot_core_dot_communication__objects_dot_helpers__pb2
from shiva.core.communication_objects import metrics_pb2 as shiva_dot_core_dot_communication__objects_dot_metrics__pb2


class MetaLearnerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetConfigs = channel.unary_unary(
        '/communication_objects.MetaLearner/GetConfigs',
        request_serializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.SimpleMessage.SerializeToString,
        response_deserializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.SimpleMessage.FromString,
        )
    self.SendSpecs = channel.unary_unary(
        '/communication_objects.MetaLearner/SendSpecs',
        request_serializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.SimpleMessage.SerializeToString,
        response_deserializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.FromString,
        )
    self.SendMetrics = channel.unary_unary(
        '/communication_objects.MetaLearner/SendMetrics',
        request_serializer=shiva_dot_core_dot_communication__objects_dot_metrics__pb2.MetricsProto.SerializeToString,
        response_deserializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.FromString,
        )


class MetaLearnerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetConfigs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendSpecs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendMetrics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MetaLearnerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetConfigs': grpc.unary_unary_rpc_method_handler(
          servicer.GetConfigs,
          request_deserializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.SimpleMessage.FromString,
          response_serializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.SimpleMessage.SerializeToString,
      ),
      'SendSpecs': grpc.unary_unary_rpc_method_handler(
          servicer.SendSpecs,
          request_deserializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.SimpleMessage.FromString,
          response_serializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.SerializeToString,
      ),
      'SendMetrics': grpc.unary_unary_rpc_method_handler(
          servicer.SendMetrics,
          request_deserializer=shiva_dot_core_dot_communication__objects_dot_metrics__pb2.MetricsProto.FromString,
          response_serializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'communication_objects.MetaLearner', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
