# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shiva/core/communication_objects/configs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shiva/core/communication_objects/configs.proto',
  package='communication_objects',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n.shiva/core/communication_objects/configs.proto\x12\x15\x63ommunication_objects\"]\n\x14NewAgentsConfigProto\x12\x32\n\tload_type\x18\x01 \x01(\x0e\x32\x1f.communication_objects.LoadType\x12\x11\n\tload_path\x18\x02 \x01(\t\"$\n\x14\x45volutionConfigProto\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"%\n\x15\x45valuationConfigProto\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t*\x1b\n\x06Status\x12\x06\n\x02OK\x10\x00\x12\t\n\x05\x45RROR\x10\x01*$\n\x08LoadType\x12\x0f\n\x0bLocalPickle\x10\x00\x12\x07\n\x03\x41WS\x10\x02\x62\x06proto3')
)

_STATUS = _descriptor.EnumDescriptor(
  name='Status',
  full_name='communication_objects.Status',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OK', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=245,
  serialized_end=272,
)
_sym_db.RegisterEnumDescriptor(_STATUS)

Status = enum_type_wrapper.EnumTypeWrapper(_STATUS)
_LOADTYPE = _descriptor.EnumDescriptor(
  name='LoadType',
  full_name='communication_objects.LoadType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LocalPickle', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AWS', index=1, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=274,
  serialized_end=310,
)
_sym_db.RegisterEnumDescriptor(_LOADTYPE)

LoadType = enum_type_wrapper.EnumTypeWrapper(_LOADTYPE)
OK = 0
ERROR = 1
LocalPickle = 0
AWS = 2



_NEWAGENTSCONFIGPROTO = _descriptor.Descriptor(
  name='NewAgentsConfigProto',
  full_name='communication_objects.NewAgentsConfigProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='load_type', full_name='communication_objects.NewAgentsConfigProto.load_type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='load_path', full_name='communication_objects.NewAgentsConfigProto.load_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=166,
)


_EVOLUTIONCONFIGPROTO = _descriptor.Descriptor(
  name='EvolutionConfigProto',
  full_name='communication_objects.EvolutionConfigProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='communication_objects.EvolutionConfigProto.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=168,
  serialized_end=204,
)


_EVALUATIONCONFIGPROTO = _descriptor.Descriptor(
  name='EvaluationConfigProto',
  full_name='communication_objects.EvaluationConfigProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='communication_objects.EvaluationConfigProto.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=206,
  serialized_end=243,
)

_NEWAGENTSCONFIGPROTO.fields_by_name['load_type'].enum_type = _LOADTYPE
DESCRIPTOR.message_types_by_name['NewAgentsConfigProto'] = _NEWAGENTSCONFIGPROTO
DESCRIPTOR.message_types_by_name['EvolutionConfigProto'] = _EVOLUTIONCONFIGPROTO
DESCRIPTOR.message_types_by_name['EvaluationConfigProto'] = _EVALUATIONCONFIGPROTO
DESCRIPTOR.enum_types_by_name['Status'] = _STATUS
DESCRIPTOR.enum_types_by_name['LoadType'] = _LOADTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

NewAgentsConfigProto = _reflection.GeneratedProtocolMessageType('NewAgentsConfigProto', (_message.Message,), {
  'DESCRIPTOR' : _NEWAGENTSCONFIGPROTO,
  '__module__' : 'shiva.core.communication_objects.configs_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.NewAgentsConfigProto)
  })
_sym_db.RegisterMessage(NewAgentsConfigProto)

EvolutionConfigProto = _reflection.GeneratedProtocolMessageType('EvolutionConfigProto', (_message.Message,), {
  'DESCRIPTOR' : _EVOLUTIONCONFIGPROTO,
  '__module__' : 'shiva.core.communication_objects.configs_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.EvolutionConfigProto)
  })
_sym_db.RegisterMessage(EvolutionConfigProto)

EvaluationConfigProto = _reflection.GeneratedProtocolMessageType('EvaluationConfigProto', (_message.Message,), {
  'DESCRIPTOR' : _EVALUATIONCONFIGPROTO,
  '__module__' : 'shiva.core.communication_objects.configs_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.EvaluationConfigProto)
  })
_sym_db.RegisterMessage(EvaluationConfigProto)


# @@protoc_insertion_point(module_scope)
