# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shiva/core/communication_objects/enums.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shiva/core/communication_objects/enums.proto',
  package='communication_objects',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,shiva/core/communication_objects/enums.proto\x12\x15\x63ommunication_objects*a\n\rComponentType\x12\x08\n\x04META\x10\x00\x12\x0b\n\x07LEARNER\x10\x01\x12\x0c\n\x08MULTIENV\x10\x02\x12\x0f\n\x0b\x45NVIRONMENT\x10\x03\x12\x0e\n\nEVALUATION\x10\x04\x12\n\n\x06\x41GENTS\x10\x05*/\n\nStatusType\x12\t\n\x05\x45RROR\x10\x00\x12\r\n\tLAUNCHING\x10\x01\x12\x07\n\x03RUN\x10\x02*4\n\x12\x45nvironmentCommand\x12\x08\n\x04STEP\x10\x00\x12\t\n\x05RESET\x10\x01\x12\t\n\x05\x43LOSE\x10\x02*\x1e\n\x08LoadType\x12\t\n\x05LOCAL\x10\x00\x12\x07\n\x03\x41WS\x10\x01\x62\x06proto3')
)

_COMPONENTTYPE = _descriptor.EnumDescriptor(
  name='ComponentType',
  full_name='communication_objects.ComponentType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='META', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LEARNER', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MULTIENV', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ENVIRONMENT', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EVALUATION', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AGENTS', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=71,
  serialized_end=168,
)
_sym_db.RegisterEnumDescriptor(_COMPONENTTYPE)

ComponentType = enum_type_wrapper.EnumTypeWrapper(_COMPONENTTYPE)
_STATUSTYPE = _descriptor.EnumDescriptor(
  name='StatusType',
  full_name='communication_objects.StatusType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ERROR', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LAUNCHING', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RUN', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=170,
  serialized_end=217,
)
_sym_db.RegisterEnumDescriptor(_STATUSTYPE)

StatusType = enum_type_wrapper.EnumTypeWrapper(_STATUSTYPE)
_ENVIRONMENTCOMMAND = _descriptor.EnumDescriptor(
  name='EnvironmentCommand',
  full_name='communication_objects.EnvironmentCommand',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STEP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESET', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=219,
  serialized_end=271,
)
_sym_db.RegisterEnumDescriptor(_ENVIRONMENTCOMMAND)

EnvironmentCommand = enum_type_wrapper.EnumTypeWrapper(_ENVIRONMENTCOMMAND)
_LOADTYPE = _descriptor.EnumDescriptor(
  name='LoadType',
  full_name='communication_objects.LoadType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='LOCAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='AWS', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=273,
  serialized_end=303,
)
_sym_db.RegisterEnumDescriptor(_LOADTYPE)

LoadType = enum_type_wrapper.EnumTypeWrapper(_LOADTYPE)
META = 0
LEARNER = 1
MULTIENV = 2
ENVIRONMENT = 3
EVALUATION = 4
AGENTS = 5
ERROR = 0
LAUNCHING = 1
RUN = 2
STEP = 0
RESET = 1
CLOSE = 2
LOCAL = 0
AWS = 1


DESCRIPTOR.enum_types_by_name['ComponentType'] = _COMPONENTTYPE
DESCRIPTOR.enum_types_by_name['StatusType'] = _STATUSTYPE
DESCRIPTOR.enum_types_by_name['EnvironmentCommand'] = _ENVIRONMENTCOMMAND
DESCRIPTOR.enum_types_by_name['LoadType'] = _LOADTYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
