# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shiva/core/communication_objects/env_step.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shiva.core.communication_objects import helpers_pb2 as shiva_dot_core_dot_communication__objects_dot_helpers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='shiva/core/communication_objects/env_step.proto',
  package='communication_objects',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n/shiva/core/communication_objects/env_step.proto\x12\x15\x63ommunication_objects\x1a.shiva/core/communication_objects/helpers.proto\"\xc8\x01\n\x11ObservationsProto\x12\x0b\n\x03str\x18\x01 \x01(\t\x12@\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x32.communication_objects.ObservationsProto.DataEntry\x12\x12\n\nstep_count\x18\x03 \x01(\x05\x1aP\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.communication_objects.ListOfFloats:\x02\x38\x01\"\xaa\x01\n\x0c\x41\x63tionsProto\x12\x0b\n\x03str\x18\x01 \x01(\t\x12;\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32-.communication_objects.ActionsProto.DataEntry\x1aP\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x32\n\x05value\x18\x02 \x01(\x0b\x32#.communication_objects.ListOfFloats:\x02\x38\x01\"\xe9\x01\n\x0f\x41gentStateProto\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x38\n\x0bobservation\x18\x02 \x01(\x0b\x32#.communication_objects.ListOfFloats\x12\x33\n\x06\x61\x63tion\x18\x03 \x01(\x0b\x32#.communication_objects.ListOfFloats\x12=\n\x10next_observation\x18\x04 \x01(\x0b\x32#.communication_objects.ListOfFloats\x12\x0e\n\x06reward\x18\x05 \x01(\x02\x12\x0c\n\x04\x64one\x18\x06 \x01(\x08\"i\n\x14\x41gentTrajectoryProto\x12\x0b\n\x03str\x18\x01 \x01(\t\x12\x34\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32&.communication_objects.AgentStateProto\x12\x0e\n\x06length\x18\x03 \x01(\x05\"\xbc\x01\n\x11TrajectoriesProto\x12\x0b\n\x03str\x18\x01 \x01(\t\x12@\n\x04\x64\x61ta\x18\x02 \x03(\x0b\x32\x32.communication_objects.TrajectoriesProto.DataEntry\x1aX\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12:\n\x05value\x18\x02 \x01(\x0b\x32+.communication_objects.AgentTrajectoryProto:\x02\x38\x01*4\n\x12\x45nvironmentCommand\x12\x08\n\x04STEP\x10\x00\x12\t\n\x05RESET\x10\x01\x12\t\n\x05\x43LOSE\x10\x02\x62\x06proto3')
  ,
  dependencies=[shiva_dot_core_dot_communication__objects_dot_helpers__pb2.DESCRIPTOR,])

_ENVIRONMENTCOMMAND = _descriptor.EnumDescriptor(
  name='EnvironmentCommand',
  full_name='communication_objects.EnvironmentCommand',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STEP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESET', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=1032,
  serialized_end=1084,
)
_sym_db.RegisterEnumDescriptor(_ENVIRONMENTCOMMAND)

EnvironmentCommand = enum_type_wrapper.EnumTypeWrapper(_ENVIRONMENTCOMMAND)
STEP = 0
RESET = 1
CLOSE = 2



_OBSERVATIONSPROTO_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='communication_objects.ObservationsProto.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='communication_objects.ObservationsProto.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='communication_objects.ObservationsProto.DataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=323,
)

_OBSERVATIONSPROTO = _descriptor.Descriptor(
  name='ObservationsProto',
  full_name='communication_objects.ObservationsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='communication_objects.ObservationsProto.str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='communication_objects.ObservationsProto.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step_count', full_name='communication_objects.ObservationsProto.step_count', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_OBSERVATIONSPROTO_DATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=323,
)


_ACTIONSPROTO_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='communication_objects.ActionsProto.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='communication_objects.ActionsProto.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='communication_objects.ActionsProto.DataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=323,
)

_ACTIONSPROTO = _descriptor.Descriptor(
  name='ActionsProto',
  full_name='communication_objects.ActionsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='communication_objects.ActionsProto.str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='communication_objects.ActionsProto.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_ACTIONSPROTO_DATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=326,
  serialized_end=496,
)


_AGENTSTATEPROTO = _descriptor.Descriptor(
  name='AgentStateProto',
  full_name='communication_objects.AgentStateProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='communication_objects.AgentStateProto.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='observation', full_name='communication_objects.AgentStateProto.observation', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='communication_objects.AgentStateProto.action', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='next_observation', full_name='communication_objects.AgentStateProto.next_observation', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward', full_name='communication_objects.AgentStateProto.reward', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='done', full_name='communication_objects.AgentStateProto.done', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=499,
  serialized_end=732,
)


_AGENTTRAJECTORYPROTO = _descriptor.Descriptor(
  name='AgentTrajectoryProto',
  full_name='communication_objects.AgentTrajectoryProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='communication_objects.AgentTrajectoryProto.str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='communication_objects.AgentTrajectoryProto.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='length', full_name='communication_objects.AgentTrajectoryProto.length', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=734,
  serialized_end=839,
)


_TRAJECTORIESPROTO_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='communication_objects.TrajectoriesProto.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='communication_objects.TrajectoriesProto.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='communication_objects.TrajectoriesProto.DataEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=942,
  serialized_end=1030,
)

_TRAJECTORIESPROTO = _descriptor.Descriptor(
  name='TrajectoriesProto',
  full_name='communication_objects.TrajectoriesProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='communication_objects.TrajectoriesProto.str', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='communication_objects.TrajectoriesProto.data', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_TRAJECTORIESPROTO_DATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=842,
  serialized_end=1030,
)

_OBSERVATIONSPROTO_DATAENTRY.fields_by_name['value'].message_type = shiva_dot_core_dot_communication__objects_dot_helpers__pb2._LISTOFFLOATS
_OBSERVATIONSPROTO_DATAENTRY.containing_type = _OBSERVATIONSPROTO
_OBSERVATIONSPROTO.fields_by_name['data'].message_type = _OBSERVATIONSPROTO_DATAENTRY
_ACTIONSPROTO_DATAENTRY.fields_by_name['value'].message_type = shiva_dot_core_dot_communication__objects_dot_helpers__pb2._LISTOFFLOATS
_ACTIONSPROTO_DATAENTRY.containing_type = _ACTIONSPROTO
_ACTIONSPROTO.fields_by_name['data'].message_type = _ACTIONSPROTO_DATAENTRY
_AGENTSTATEPROTO.fields_by_name['observation'].message_type = shiva_dot_core_dot_communication__objects_dot_helpers__pb2._LISTOFFLOATS
_AGENTSTATEPROTO.fields_by_name['action'].message_type = shiva_dot_core_dot_communication__objects_dot_helpers__pb2._LISTOFFLOATS
_AGENTSTATEPROTO.fields_by_name['next_observation'].message_type = shiva_dot_core_dot_communication__objects_dot_helpers__pb2._LISTOFFLOATS
_AGENTTRAJECTORYPROTO.fields_by_name['data'].message_type = _AGENTSTATEPROTO
_TRAJECTORIESPROTO_DATAENTRY.fields_by_name['value'].message_type = _AGENTTRAJECTORYPROTO
_TRAJECTORIESPROTO_DATAENTRY.containing_type = _TRAJECTORIESPROTO
_TRAJECTORIESPROTO.fields_by_name['data'].message_type = _TRAJECTORIESPROTO_DATAENTRY
DESCRIPTOR.message_types_by_name['ObservationsProto'] = _OBSERVATIONSPROTO
DESCRIPTOR.message_types_by_name['ActionsProto'] = _ACTIONSPROTO
DESCRIPTOR.message_types_by_name['AgentStateProto'] = _AGENTSTATEPROTO
DESCRIPTOR.message_types_by_name['AgentTrajectoryProto'] = _AGENTTRAJECTORYPROTO
DESCRIPTOR.message_types_by_name['TrajectoriesProto'] = _TRAJECTORIESPROTO
DESCRIPTOR.enum_types_by_name['EnvironmentCommand'] = _ENVIRONMENTCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ObservationsProto = _reflection.GeneratedProtocolMessageType('ObservationsProto', (_message.Message,), {

  'DataEntry' : _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
    'DESCRIPTOR' : _OBSERVATIONSPROTO_DATAENTRY,
    '__module__' : 'shiva.core.communication_objects.env_step_pb2'
    # @@protoc_insertion_point(class_scope:communication_objects.ObservationsProto.DataEntry)
    })
  ,
  'DESCRIPTOR' : _OBSERVATIONSPROTO,
  '__module__' : 'shiva.core.communication_objects.env_step_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.ObservationsProto)
  })
_sym_db.RegisterMessage(ObservationsProto)
_sym_db.RegisterMessage(ObservationsProto.DataEntry)

ActionsProto = _reflection.GeneratedProtocolMessageType('ActionsProto', (_message.Message,), {

  'DataEntry' : _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
    'DESCRIPTOR' : _ACTIONSPROTO_DATAENTRY,
    '__module__' : 'shiva.core.communication_objects.env_step_pb2'
    # @@protoc_insertion_point(class_scope:communication_objects.ActionsProto.DataEntry)
    })
  ,
  'DESCRIPTOR' : _ACTIONSPROTO,
  '__module__' : 'shiva.core.communication_objects.env_step_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.ActionsProto)
  })
_sym_db.RegisterMessage(ActionsProto)
_sym_db.RegisterMessage(ActionsProto.DataEntry)

AgentStateProto = _reflection.GeneratedProtocolMessageType('AgentStateProto', (_message.Message,), {
  'DESCRIPTOR' : _AGENTSTATEPROTO,
  '__module__' : 'shiva.core.communication_objects.env_step_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.AgentStateProto)
  })
_sym_db.RegisterMessage(AgentStateProto)

AgentTrajectoryProto = _reflection.GeneratedProtocolMessageType('AgentTrajectoryProto', (_message.Message,), {
  'DESCRIPTOR' : _AGENTTRAJECTORYPROTO,
  '__module__' : 'shiva.core.communication_objects.env_step_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.AgentTrajectoryProto)
  })
_sym_db.RegisterMessage(AgentTrajectoryProto)

TrajectoriesProto = _reflection.GeneratedProtocolMessageType('TrajectoriesProto', (_message.Message,), {

  'DataEntry' : _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
    'DESCRIPTOR' : _TRAJECTORIESPROTO_DATAENTRY,
    '__module__' : 'shiva.core.communication_objects.env_step_pb2'
    # @@protoc_insertion_point(class_scope:communication_objects.TrajectoriesProto.DataEntry)
    })
  ,
  'DESCRIPTOR' : _TRAJECTORIESPROTO,
  '__module__' : 'shiva.core.communication_objects.env_step_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.TrajectoriesProto)
  })
_sym_db.RegisterMessage(TrajectoriesProto)
_sym_db.RegisterMessage(TrajectoriesProto.DataEntry)


_OBSERVATIONSPROTO_DATAENTRY._options = None
_ACTIONSPROTO_DATAENTRY._options = None
_TRAJECTORIESPROTO_DATAENTRY._options = None
# @@protoc_insertion_point(module_scope)
