# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shiva/core/communication_objects/env_metrics.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shiva/core/communication_objects/env_metrics.proto',
  package='communication_objects',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n2shiva/core/communication_objects/env_metrics.proto\x12\x15\x63ommunication_objects\"\xb7\x01\n\x0c\x41gentMetrics\x12\x19\n\x11steps_per_episode\x18\x01 \x01(\x02\x12\x12\n\nstep_count\x18\x02 \x01(\x02\x12\x19\n\x11temp_done_counter\x18\x03 \x01(\x02\x12\x12\n\ndone_count\x18\x04 \x01(\x02\x12\x17\n\x0freward_per_step\x18\x05 \x01(\x02\x12\x1a\n\x12reward_per_episode\x18\x06 \x01(\x02\x12\x14\n\x0creward_total\x18\x07 \x01(\x02\x62\x06proto3')
)




_AGENTMETRICS = _descriptor.Descriptor(
  name='AgentMetrics',
  full_name='communication_objects.AgentMetrics',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='steps_per_episode', full_name='communication_objects.AgentMetrics.steps_per_episode', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='step_count', full_name='communication_objects.AgentMetrics.step_count', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp_done_counter', full_name='communication_objects.AgentMetrics.temp_done_counter', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='done_count', full_name='communication_objects.AgentMetrics.done_count', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward_per_step', full_name='communication_objects.AgentMetrics.reward_per_step', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward_per_episode', full_name='communication_objects.AgentMetrics.reward_per_episode', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='reward_total', full_name='communication_objects.AgentMetrics.reward_total', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=78,
  serialized_end=261,
)

DESCRIPTOR.message_types_by_name['AgentMetrics'] = _AGENTMETRICS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AgentMetrics = _reflection.GeneratedProtocolMessageType('AgentMetrics', (_message.Message,), {
  'DESCRIPTOR' : _AGENTMETRICS,
  '__module__' : 'shiva.core.communication_objects.env_metrics_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.AgentMetrics)
  })
_sym_db.RegisterMessage(AgentMetrics)


# @@protoc_insertion_point(module_scope)
