# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shiva/core/communication_objects/env_command.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shiva/core/communication_objects/env_command.proto',
  package='communication_objects',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n2shiva/core/communication_objects/env_command.proto\x12\x15\x63ommunication_objects*4\n\x12\x45nvironmentCommand\x12\x08\n\x04STEP\x10\x00\x12\t\n\x05RESET\x10\x01\x12\t\n\x05\x43LOSE\x10\x02\x62\x06proto3')
)

_ENVIRONMENTCOMMAND = _descriptor.EnumDescriptor(
  name='EnvironmentCommand',
  full_name='communication_objects.EnvironmentCommand',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='STEP', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RESET', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='CLOSE', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=77,
  serialized_end=129,
)
_sym_db.RegisterEnumDescriptor(_ENVIRONMENTCOMMAND)

EnvironmentCommand = enum_type_wrapper.EnumTypeWrapper(_ENVIRONMENTCOMMAND)
STEP = 0
RESET = 1
CLOSE = 2


DESCRIPTOR.enum_types_by_name['EnvironmentCommand'] = _ENVIRONMENTCOMMAND
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
