# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from shiva.core.communication_objects import env_specs_pb2 as shiva_dot_core_dot_communication__objects_dot_env__specs__pb2
from shiva.core.communication_objects import env_step_pb2 as shiva_dot_core_dot_communication__objects_dot_env__step__pb2
from shiva.core.communication_objects import helpers_pb2 as shiva_dot_core_dot_communication__objects_dot_helpers__pb2


class EnvironmentStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetSpecs = channel.unary_unary(
        '/communication_objects.Environment/GetSpecs',
        request_serializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.SerializeToString,
        response_deserializer=shiva_dot_core_dot_communication__objects_dot_env__specs__pb2.EnvironmentSpecs.FromString,
        )
    self.Step = channel.unary_unary(
        '/communication_objects.Environment/Step',
        request_serializer=shiva_dot_core_dot_communication__objects_dot_env__step__pb2.EnvStepInput.SerializeToString,
        response_deserializer=shiva_dot_core_dot_communication__objects_dot_env__step__pb2.EnvStepOutput.FromString,
        )
    self.Reset = channel.unary_unary(
        '/communication_objects.Environment/Reset',
        request_serializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.SerializeToString,
        response_deserializer=shiva_dot_core_dot_communication__objects_dot_env__step__pb2.EnvStepOutput.FromString,
        )


class EnvironmentServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetSpecs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Step(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Reset(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_EnvironmentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetSpecs': grpc.unary_unary_rpc_method_handler(
          servicer.GetSpecs,
          request_deserializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.FromString,
          response_serializer=shiva_dot_core_dot_communication__objects_dot_env__specs__pb2.EnvironmentSpecs.SerializeToString,
      ),
      'Step': grpc.unary_unary_rpc_method_handler(
          servicer.Step,
          request_deserializer=shiva_dot_core_dot_communication__objects_dot_env__step__pb2.EnvStepInput.FromString,
          response_serializer=shiva_dot_core_dot_communication__objects_dot_env__step__pb2.EnvStepOutput.SerializeToString,
      ),
      'Reset': grpc.unary_unary_rpc_method_handler(
          servicer.Reset,
          request_deserializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.FromString,
          response_serializer=shiva_dot_core_dot_communication__objects_dot_env__step__pb2.EnvStepOutput.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'communication_objects.Environment', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
