# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from shiva.core.communication_objects import configs_pb2 as shiva_dot_core_dot_communication__objects_dot_configs__pb2
from shiva.core.communication_objects import env_step_pb2 as shiva_dot_core_dot_communication__objects_dot_env__step__pb2
from shiva.core.communication_objects import helpers_pb2 as shiva_dot_core_dot_communication__objects_dot_helpers__pb2


class MultiEnvironmentStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendObservations = channel.unary_unary(
        '/communication_objects.MultiEnvironment/SendObservations',
        request_serializer=shiva_dot_core_dot_communication__objects_dot_env__step__pb2.ObservationsProto.SerializeToString,
        response_deserializer=shiva_dot_core_dot_communication__objects_dot_env__step__pb2.ActionsProto.FromString,
        )
    self.SendNewAgents = channel.unary_unary(
        '/communication_objects.MultiEnvironment/SendNewAgents',
        request_serializer=shiva_dot_core_dot_communication__objects_dot_configs__pb2.NewAgentsConfigProto.SerializeToString,
        response_deserializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.FromString,
        )


class MultiEnvironmentServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendObservations(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendNewAgents(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MultiEnvironmentServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendObservations': grpc.unary_unary_rpc_method_handler(
          servicer.SendObservations,
          request_deserializer=shiva_dot_core_dot_communication__objects_dot_env__step__pb2.ObservationsProto.FromString,
          response_serializer=shiva_dot_core_dot_communication__objects_dot_env__step__pb2.ActionsProto.SerializeToString,
      ),
      'SendNewAgents': grpc.unary_unary_rpc_method_handler(
          servicer.SendNewAgents,
          request_deserializer=shiva_dot_core_dot_communication__objects_dot_configs__pb2.NewAgentsConfigProto.FromString,
          response_serializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'communication_objects.MultiEnvironment', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
