# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shiva/core/communication_objects/service_iohandler.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shiva.core.communication_objects import helpers_pb2 as shiva_dot_core_dot_communication__objects_dot_helpers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='shiva/core/communication_objects/service_iohandler.proto',
  package='communication_objects',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n8shiva/core/communication_objects/service_iohandler.proto\x12\x15\x63ommunication_objects\x1a.shiva/core/communication_objects/helpers.proto2\xb5\x01\n\tIOHandler\x12Z\n\x0c\x41skIORequest\x12$.communication_objects.SimpleMessage\x1a$.communication_objects.SimpleMessage\x12L\n\x06\x44oneIO\x12$.communication_objects.SimpleMessage\x1a\x1c.communication_objects.Emptyb\x06proto3')
  ,
  dependencies=[shiva_dot_core_dot_communication__objects_dot_helpers__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_IOHANDLER = _descriptor.ServiceDescriptor(
  name='IOHandler',
  full_name='communication_objects.IOHandler',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=132,
  serialized_end=313,
  methods=[
  _descriptor.MethodDescriptor(
    name='AskIORequest',
    full_name='communication_objects.IOHandler.AskIORequest',
    index=0,
    containing_service=None,
    input_type=shiva_dot_core_dot_communication__objects_dot_helpers__pb2._SIMPLEMESSAGE,
    output_type=shiva_dot_core_dot_communication__objects_dot_helpers__pb2._SIMPLEMESSAGE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='DoneIO',
    full_name='communication_objects.IOHandler.DoneIO',
    index=1,
    containing_service=None,
    input_type=shiva_dot_core_dot_communication__objects_dot_helpers__pb2._SIMPLEMESSAGE,
    output_type=shiva_dot_core_dot_communication__objects_dot_helpers__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IOHANDLER)

DESCRIPTOR.services_by_name['IOHandler'] = _IOHANDLER

# @@protoc_insertion_point(module_scope)
