# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shiva/core/communication_objects/service_env.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shiva.core.communication_objects import env_step_pb2 as shiva_dot_core_dot_communication__objects_dot_env__step__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='shiva/core/communication_objects/service_env.proto',
  package='communication_objects',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n2shiva/core/communication_objects/service_env.proto\x12\x15\x63ommunication_objects\x1a/shiva/core/communication_objects/env_step.proto2b\n\x0b\x45nvironment\x12S\n\x04Step\x12#.communication_objects.EnvStepInput\x1a$.communication_objects.EnvStepOutput\"\x00\x62\x06proto3')
  ,
  dependencies=[shiva_dot_core_dot_communication__objects_dot_env__step__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_ENVIRONMENT = _descriptor.ServiceDescriptor(
  name='Environment',
  full_name='communication_objects.Environment',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=126,
  serialized_end=224,
  methods=[
  _descriptor.MethodDescriptor(
    name='Step',
    full_name='communication_objects.Environment.Step',
    index=0,
    containing_service=None,
    input_type=shiva_dot_core_dot_communication__objects_dot_env__step__pb2._ENVSTEPINPUT,
    output_type=shiva_dot_core_dot_communication__objects_dot_env__step__pb2._ENVSTEPOUTPUT,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ENVIRONMENT)

DESCRIPTOR.services_by_name['Environment'] = _ENVIRONMENT

# @@protoc_insertion_point(module_scope)
