# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from shiva.core.communication_objects import env_specs_pb2 as shiva_dot_core_dot_communication__objects_dot_env__specs__pb2
from shiva.core.communication_objects import helpers_pb2 as shiva_dot_core_dot_communication__objects_dot_helpers__pb2
from shiva.core.communication_objects import metrics_pb2 as shiva_dot_core_dot_communication__objects_dot_metrics__pb2


class MetaLearnerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.SendMultiEnvSpecs = channel.unary_unary(
        '/communication_objects.MetaLearner/SendMultiEnvSpecs',
        request_serializer=shiva_dot_core_dot_communication__objects_dot_env__specs__pb2.MultiEnvSpecsProto.SerializeToString,
        response_deserializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.FromString,
        )
    self.SendTrainingMetrics = channel.unary_unary(
        '/communication_objects.MetaLearner/SendTrainingMetrics',
        request_serializer=shiva_dot_core_dot_communication__objects_dot_metrics__pb2.TrainingMetricsProto.SerializeToString,
        response_deserializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.FromString,
        )
    self.SendEvaluationMetrics = channel.unary_unary(
        '/communication_objects.MetaLearner/SendEvaluationMetrics',
        request_serializer=shiva_dot_core_dot_communication__objects_dot_metrics__pb2.EvaluationMetricsProto.SerializeToString,
        response_deserializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.FromString,
        )


class MetaLearnerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def SendMultiEnvSpecs(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendTrainingMetrics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendEvaluationMetrics(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_MetaLearnerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'SendMultiEnvSpecs': grpc.unary_unary_rpc_method_handler(
          servicer.SendMultiEnvSpecs,
          request_deserializer=shiva_dot_core_dot_communication__objects_dot_env__specs__pb2.MultiEnvSpecsProto.FromString,
          response_serializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.SerializeToString,
      ),
      'SendTrainingMetrics': grpc.unary_unary_rpc_method_handler(
          servicer.SendTrainingMetrics,
          request_deserializer=shiva_dot_core_dot_communication__objects_dot_metrics__pb2.TrainingMetricsProto.FromString,
          response_serializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.SerializeToString,
      ),
      'SendEvaluationMetrics': grpc.unary_unary_rpc_method_handler(
          servicer.SendEvaluationMetrics,
          request_deserializer=shiva_dot_core_dot_communication__objects_dot_metrics__pb2.EvaluationMetricsProto.FromString,
          response_serializer=shiva_dot_core_dot_communication__objects_dot_helpers__pb2.Empty.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'communication_objects.MetaLearner', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
