# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shiva/core/communication_objects/service_learner.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from shiva.core.communication_objects import helpers_pb2 as shiva_dot_core_dot_communication__objects_dot_helpers__pb2
from shiva.core.communication_objects import configs_pb2 as shiva_dot_core_dot_communication__objects_dot_configs__pb2
from shiva.core.communication_objects import specs_pb2 as shiva_dot_core_dot_communication__objects_dot_specs__pb2
from shiva.core.communication_objects import env_step_pb2 as shiva_dot_core_dot_communication__objects_dot_env__step__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='shiva/core/communication_objects/service_learner.proto',
  package='communication_objects',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n6shiva/core/communication_objects/service_learner.proto\x12\x15\x63ommunication_objects\x1a.shiva/core/communication_objects/helpers.proto\x1a.shiva/core/communication_objects/configs.proto\x1a,shiva/core/communication_objects/specs.proto\x1a/shiva/core/communication_objects/env_step.proto2\x97\x02\n\x07Learner\x12W\n\x11SendMultiEnvSpecs\x12$.communication_objects.EnvSpecsProto\x1a\x1c.communication_objects.Empty\x12W\n\x13SendEvolutionConfig\x12\".communication_objects.ConfigProto\x1a\x1c.communication_objects.Empty\x12Z\n\x10SendTrajectories\x12(.communication_objects.TrajectoriesProto\x1a\x1c.communication_objects.Emptyb\x06proto3')
  ,
  dependencies=[shiva_dot_core_dot_communication__objects_dot_helpers__pb2.DESCRIPTOR,shiva_dot_core_dot_communication__objects_dot_configs__pb2.DESCRIPTOR,shiva_dot_core_dot_communication__objects_dot_specs__pb2.DESCRIPTOR,shiva_dot_core_dot_communication__objects_dot_env__step__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_LEARNER = _descriptor.ServiceDescriptor(
  name='Learner',
  full_name='communication_objects.Learner',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=273,
  serialized_end=552,
  methods=[
  _descriptor.MethodDescriptor(
    name='SendMultiEnvSpecs',
    full_name='communication_objects.Learner.SendMultiEnvSpecs',
    index=0,
    containing_service=None,
    input_type=shiva_dot_core_dot_communication__objects_dot_specs__pb2._ENVSPECSPROTO,
    output_type=shiva_dot_core_dot_communication__objects_dot_helpers__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendEvolutionConfig',
    full_name='communication_objects.Learner.SendEvolutionConfig',
    index=1,
    containing_service=None,
    input_type=shiva_dot_core_dot_communication__objects_dot_configs__pb2._CONFIGPROTO,
    output_type=shiva_dot_core_dot_communication__objects_dot_helpers__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendTrajectories',
    full_name='communication_objects.Learner.SendTrajectories',
    index=2,
    containing_service=None,
    input_type=shiva_dot_core_dot_communication__objects_dot_env__step__pb2._TRAJECTORIESPROTO,
    output_type=shiva_dot_core_dot_communication__objects_dot_helpers__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_LEARNER)

DESCRIPTOR.services_by_name['Learner'] = _LEARNER

# @@protoc_insertion_point(module_scope)
