# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shiva/core/communication_objects/specs.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='shiva/core/communication_objects/specs.proto',
  package='communication_objects',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n,shiva/core/communication_objects/specs.proto\x12\x15\x63ommunication_objects\"F\n\x10\x41\x63tionSpaceProto\x12\x10\n\x08\x64iscrete\x18\x01 \x01(\x05\x12\r\n\x05param\x18\x02 \x01(\x05\x12\x11\n\tacs_space\x18\x03 \x01(\x05\"}\n\rEnvSpecsProto\x12\x19\n\x11observation_space\x18\x01 \x01(\x05\x12=\n\x0c\x61\x63tion_space\x18\x02 \x01(\x0b\x32\'.communication_objects.ActionSpaceProto\x12\x12\n\nnum_agents\x18\x03 \x01(\x05\"_\n\x12MultiEnvSpecsProto\x12\x37\n\tenv_specs\x18\x01 \x01(\x0b\x32$.communication_objects.EnvSpecsProto\x12\x10\n\x08num_envs\x18\x02 \x01(\x05\"!\n\x11LearnerSpecsProto\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\tb\x06proto3')
)




_ACTIONSPACEPROTO = _descriptor.Descriptor(
  name='ActionSpaceProto',
  full_name='communication_objects.ActionSpaceProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='discrete', full_name='communication_objects.ActionSpaceProto.discrete', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='param', full_name='communication_objects.ActionSpaceProto.param', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acs_space', full_name='communication_objects.ActionSpaceProto.acs_space', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=141,
)


_ENVSPECSPROTO = _descriptor.Descriptor(
  name='EnvSpecsProto',
  full_name='communication_objects.EnvSpecsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='observation_space', full_name='communication_objects.EnvSpecsProto.observation_space', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action_space', full_name='communication_objects.EnvSpecsProto.action_space', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_agents', full_name='communication_objects.EnvSpecsProto.num_agents', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=268,
)


_MULTIENVSPECSPROTO = _descriptor.Descriptor(
  name='MultiEnvSpecsProto',
  full_name='communication_objects.MultiEnvSpecsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='env_specs', full_name='communication_objects.MultiEnvSpecsProto.env_specs', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='num_envs', full_name='communication_objects.MultiEnvSpecsProto.num_envs', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=365,
)


_LEARNERSPECSPROTO = _descriptor.Descriptor(
  name='LearnerSpecsProto',
  full_name='communication_objects.LearnerSpecsProto',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='communication_objects.LearnerSpecsProto.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=367,
  serialized_end=400,
)

_ENVSPECSPROTO.fields_by_name['action_space'].message_type = _ACTIONSPACEPROTO
_MULTIENVSPECSPROTO.fields_by_name['env_specs'].message_type = _ENVSPECSPROTO
DESCRIPTOR.message_types_by_name['ActionSpaceProto'] = _ACTIONSPACEPROTO
DESCRIPTOR.message_types_by_name['EnvSpecsProto'] = _ENVSPECSPROTO
DESCRIPTOR.message_types_by_name['MultiEnvSpecsProto'] = _MULTIENVSPECSPROTO
DESCRIPTOR.message_types_by_name['LearnerSpecsProto'] = _LEARNERSPECSPROTO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ActionSpaceProto = _reflection.GeneratedProtocolMessageType('ActionSpaceProto', (_message.Message,), {
  'DESCRIPTOR' : _ACTIONSPACEPROTO,
  '__module__' : 'shiva.core.communication_objects.specs_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.ActionSpaceProto)
  })
_sym_db.RegisterMessage(ActionSpaceProto)

EnvSpecsProto = _reflection.GeneratedProtocolMessageType('EnvSpecsProto', (_message.Message,), {
  'DESCRIPTOR' : _ENVSPECSPROTO,
  '__module__' : 'shiva.core.communication_objects.specs_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.EnvSpecsProto)
  })
_sym_db.RegisterMessage(EnvSpecsProto)

MultiEnvSpecsProto = _reflection.GeneratedProtocolMessageType('MultiEnvSpecsProto', (_message.Message,), {
  'DESCRIPTOR' : _MULTIENVSPECSPROTO,
  '__module__' : 'shiva.core.communication_objects.specs_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.MultiEnvSpecsProto)
  })
_sym_db.RegisterMessage(MultiEnvSpecsProto)

LearnerSpecsProto = _reflection.GeneratedProtocolMessageType('LearnerSpecsProto', (_message.Message,), {
  'DESCRIPTOR' : _LEARNERSPECSPROTO,
  '__module__' : 'shiva.core.communication_objects.specs_pb2'
  # @@protoc_insertion_point(class_scope:communication_objects.LearnerSpecsProto)
  })
_sym_db.RegisterMessage(LearnerSpecsProto)


# @@protoc_insertion_point(module_scope)
